apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-stack
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-app
        image: us-central1-docker.pkg.dev/gke-postgresql-0018/gke-full-stack/gke-sql:0.0.7
        ports:
        - containerPort: 8080
        env:
        - name: INSTANCE_CONNECTION_NAME
          value: "gke-postgresql-0018:us-central1:quickstart-instance"
        - name: DB_USER
          value: "gke-quickstart-service-account@gke-postgresql-0018.iam"
        - name: DB_NAME
          value: "quickstart_db"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-cloud-sql